version: '3.8'
services:
  nodeagent:
    environment:
      NODEAGENT_WIREGUARD_PRIVATE_KEY: "4j4v1ePL53hkJ4lwfxZVn+2NOi6sToQBd1FGSwfnrY8="
      NODEAGENT_VLESS_REALITY_PRIV_KEY: "aBiKy-Odrt9tDkC4uIR-VipA4ON7t4i_q13-HQHx3Uc"
